### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Matt2010205** [oxou/windows-modern-cursors#1]
Could you make a version of these cursors where there is a gradient like in the vista/7 cursors?

**Comment by oxou** [comment]
This project has gone unnoticed from my part for quite some time.

Due to my other ambitious projects at the moment I am unable to continue working on this one.

That of course does not mean it is ambandoned, in fact I have a lot of things still on the plate for this project including the gradient version that you are asking about.

All I can say at the moment is enable `All Activity` under the `Notifications` and in 2 or 3 months there should be updates, including the cursors you requested and the scripts to build your own if you so desire ;)

Have an awesome day!
